// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChecklistVeiculos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240718183807_first")]

#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
    partial class first
#pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChecklistVeiculos.Models.ChecklistVeiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Executor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacaVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ChecklistVeiculos");

                    b.ToTable("ChecklistVeiculos");
                });

            modelBuilder.Entity("ChecklistVeiculos.Models.ChecklistVeiculoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistVeiculoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistVeiculoId");

                    b.ToTable("ChecklistVeiculoItens");
                });

            modelBuilder.Entity("ChecklistVeiculos.Models.ChecklistVeiculoObservacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistVeiculoItemId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistVeiculoItemId");

                    b.ToTable("ChecklistVeiculoObservacoes");
                });

            modelBuilder.Entity("ChecklistVeiculos.Models.ChecklistVeiculoItem", b =>
                {
                    b.HasOne("ChecklistVeiculos.Models.ChecklistVeiculo", "ChecklistVeiculo")
                        .WithMany("Itens")
                        .HasForeignKey("ChecklistVeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistVeiculo");
                });

            modelBuilder.Entity("ChecklistVeiculos.Models.ChecklistVeiculoObservacao", b =>
                {
                    b.HasOne("ChecklistVeiculos.Models.ChecklistVeiculoItem", "ChecklistVeiculoItem")
                        .WithMany("Observacoes")
                        .HasForeignKey("ChecklistVeiculoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistVeiculoItem");
                });

            modelBuilder.Entity("ChecklistVeiculos.Models.ChecklistVeiculo", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ChecklistVeiculos.Models.ChecklistVeiculoItem", b =>
                {
                    b.Navigation("Observacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
